### ISSUE TITLE
Masthead Semantics 

### ISSUE THREAD

**Issue by imagineW** [imagineW/first-respository#2]
<img width="792" alt="screen shot 2017-09-25 at 2 22 55 pm" src="https://user-images.githubusercontent.com/31852629/30824425-9ab2c6ae-a1fd-11e7-96ee-1bfd6eddeb68.png">

<img width="704" alt="screen shot 2017-09-25 at 2 30 51 pm" src="https://user-images.githubusercontent.com/31852629/30824712-6ca8af52-a1fe-11e7-9527-5fed97f831f4.png">

<img width="685" alt="screen shot 2017-09-25 at 2 31 14 pm" src="https://user-images.githubusercontent.com/31852629/30824719-6f0e7f38-a1fe-11e7-917e-c27abae5de3f.png">

<img width="696" alt="screen shot 2017-09-25 at 2 31 32 pm" src="https://user-images.githubusercontent.com/31852629/30824723-711c755a-a1fe-11e7-8439-b2dfbaecc611.png">

I wasn't able to finish this assignment by the end of class today. I am still having difficulty and I don't know how to fix the problems that Markbot keeps telling me to fix. May

 you please direct me. Thank you. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
I'd be happy to help, but this issue isn't attached to the correct assignment—so I can't see the code. The issue is on the `first-repository` repo, but I believe the problem is on the `masthead-semantics` repo. 

Go to the `masthead-semantics` repo, turn on Issues there, and write the description there. That will allow me to see the code and navigate around to help you debug.
